onboard centos stream 8 and 9
kubevirt/containerdisks pull request #12
Opened 2022-01-04 13:31 UTC by ksimon1

This PR adds support for centos stream 8 and 9

Signed-off-by: Karel Šimon <ksimon@redhat.com>

2022-01-04 13:36 UTC, ksimon1 commented
/cc @rmohr @dominikholler

2022-01-04 21:48 UTC, dominikholler requested changes
@ksimon1 thanks for the PR, looks good, the resulting docs looks fine and the produced images works. Would be nice if you could address the three nits.

2022-01-04 21:48 UTC, dominikholler commented on artifacts/centosstream/centos-stream.go
> +// New accepts CentOS 7 and 8 versions. Example patterns are 7-2111, 7-2009, 8.3, 8.4, ...
This comment should be adjusted to centos stream, e.g.
```
// New accepts CentOS Stream 8 and 9 versions.
```

2022-01-04 21:48 UTC, dominikholler commented on cmd/medius/common/registry.go
> +		UseForDocs: true,
We want to use only centos 9 in docs.

```
UseForDocs: false,
```

2022-01-04 21:48 UTC, dominikholler commented on cmd/medius/common/registry.go
> +		Artifact:   centosstream.New("9"),
Maybe the order of ... centos 8, centos 7, centos-stream 9, centos streram 8 is more intuitive.

2022-01-07 13:36 UTC, dominikholler approved these changes
/lgtm

2022-01-07 21:12 UTC, dominikholler commented
only errors like "error introspecting image \"quay.io/containerdisks/centos-stream:9\": error parsing image: reading manifest 9 in quay.io/containerdisks/centos-stream: unauthorized: access to the requested resource is not authorized" , which looks fine to me.

2022-01-10 08:42 UTC, rmohr commented
/retest

2022-01-10 08:50 UTC, rmohr approved these changes
Two changes could be made which apply to the containerdisk resolvers which I wrote too. We can do that in a follow-up.

2022-01-10 08:50 UTC, rmohr commented on artifacts/centosstream/centos-stream.go
> +		baseURL = fmt.Sprintf("https://cloud.centos.org/centos/%s-stream/x86_64/images/", c.Version)
`c.Arch` could be used here.

2022-01-10 08:50 UTC, rmohr commented on artifacts/centosstream/centos-stream.go
> +	additionalTag := strings.TrimSuffix(strings.TrimPrefix(candidate, fmt.Sprintf("CentOS-Stream-%s-", c.Variant)), ".x86_64.qcow2")
`c.Arch` could be used here.

2022-01-10 08:51 UTC, rmohr commented
/approve

2022-01-10 08:51 UTC, rmohr commented
@ksimon1 @dominikholler looks great :+1:

2022-01-10 08:52 UTC, merged